### Site metadata ###

title: Jekyll Blog Demo ğŸ§ª ğŸ“ ğŸš€
description: Starter for a static website or blog - built with Jekyll, a minimal theme and GH Pages

email:
twitter_username:
github_username: MichaelCurrin
rss: RSS

### Build settings ###

url: https://michaelcurrin.github.io
baseurl: /jekyll-blog-demo

permalink: pretty

theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  tools:
    output: true
  languages:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: page

# Overriding Gemfile.lock is implied.
exclude:
  - docs/
  - vendor/
  - Gemfile
  - LICENSE
  - Makefile
  - README.md
  - sample*.png

liquid:
  error_mode: strict

strict_front_matter: true
